In [11]:
import matplotlib.image as image
import PIL 
import numpy as np

In [12]:
img=image.imread('c-d-x-PDX_a_82obo-unsplash.jpg')
print('The Shape of the image is:',img.shape)
print('The image as array is:')
print(img)

The Shape of the image is: (3840, 5760, 3)
The image as array is:
[[[254 203   0]
  [254 203   0]
  [254 203   0]
  ...
  [252 195   0]
  [252 195   0]
  [252 195   0]]

 [[254 203   0]
  [254 203   0]
  [254 203   0]
  ...
  [252 195   0]
  [252 195   0]
  [252 195   0]]

 [[254 203   0]
  [254 203   0]
  [254 203   0]
  ...
  [252 195   0]
  [252 195   0]
  [252 195   0]]

 ...

 [[225 168   0]
  [225 168   0]
  [225 168   0]
  ...
  [216 162   1]
  [216 162   1]
  [216 162   1]]

 [[225 168   0]
  [225 168   0]
  [225 168   0]
  ...
  [216 162   1]
  [216 162   1]
  [216 162   1]]

 [[224 167   0]
  [225 168   0]
  [225 168   0]
  ...
  [216 162   1]
  [216 162   1]
  [216 162   1]]]


In [13]:
np.transpose(img)

array([[[254, 254, 254, ..., 225, 225, 224],
        [254, 254, 254, ..., 225, 225, 225],
        [254, 254, 254, ..., 225, 225, 225],
        ...,
        [252, 252, 252, ..., 216, 216, 216],
        [252, 252, 252, ..., 216, 216, 216],
        [252, 252, 252, ..., 216, 216, 216]],

       [[203, 203, 203, ..., 168, 168, 167],
        [203, 203, 203, ..., 168, 168, 168],
        [203, 203, 203, ..., 168, 168, 168],
        ...,
        [195, 195, 195, ..., 162, 162, 162],
        [195, 195, 195, ..., 162, 162, 162],
        [195, 195, 195, ..., 162, 162, 162]],

       [[  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        ...,
        [  0,   0,   0, ...,   1,   1,   1],
        [  0,   0,   0, ...,   1,   1,   1],
        [  0,   0,   0, ...,   1,   1,   1]]], dtype=uint8)

****Diagonal Matrix****

In [14]:
def isDiagonal(x):
    a = np.shape(x)
    size = 1 
    for i in range(len(a)):
        size = a[i] * size
    non_zero = np.count_nonzero(x - np.diag(np.diagonal(x)))
    if (non_zero == 0):
        return print("The matrix is diagonal")
    elif (non_zero != 0):
        return print("The matrix is not diagonal")
isDiagonal(img)

The matrix is not diagonal


**Triangular matrix**

**To check if a matrix is square**


In [15]:
#To check if a matrix is square
def is_square(mat):
    return all([len(i)==len(mat) for i in mat])

In [16]:
# To check if a matrix is upper triangular
def isUpperTriangular(M):
    if (is_square(M)): # to check if the matrix is sequar
        for i in range(1, len(M)):
            for j in range(0, i):
                if(np.all(M[i][j]) != 0):
                        return False
        return True
    else:
        return "The matrix is not Upper triangulaire"


In [17]:
isUpperTriangular(img)

'The matrix is not Upper triangulaire'

In [18]:
# To check if a matrix is lower triangular
def isLowerTriangular(M):
    if (is_square(M)): # to check if the matrix is sequar
        for i in range(1, len(M)):
            for j in range(i + 1, len(M)):
                if(np.all(M[i][j]) != 0):
                        return False
        return True
    else:
        return "The matrix is not Lower triangulaire"

In [19]:
isLowerTriangular(img)

'The matrix is not Lower triangulaire'

**Identity matrix**

**L1 NORM**

In [20]:
from numpy.linalg import norm
a = np.array(img[1])
l1 = norm(a,1)
l1

1467212.0

**L2 NORM**

In [21]:
l2 = norm(img[1])
l2

26140.358777185902